---
title: "Advanced R 研讨"
subtitle: "练习一"
author: "赵孟韬"
output: 
  pdf_document: 
    latex_engine: xelatex
    toc: yes
header-includes:
- \usepackage{xeCJK}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo =T,eval = FALSE)
```


## 题目

- 求同一类资产同时出现在一个时间范围的最大次数及所在id。如下面样例数据中dow这个产品在id=c(30,40,50) 这三个区间中都出现，同时dow这个产品在id=c(30,40,60)这三个区间也同时出现过（所谓同时出现，就是这几个id时间范围有重叠区间）。因此，dow在同时出现在一个时间范围的最大次数为3，所在id为：id=c(30,40,50)以及id=c(30,40,60)。建议同学先把样本数据print出来看下数据结构，再看题目。有疑问先在群上提问，把题目弄清楚了，再下笔写程序。

- 可以使用向量、dplyr、data.table、Rcpp等工具实现



```{r}
#样本数据
ds<-data.frame(id=seq(10,80,by=10),
               anest=c("baker","baker",rep("dow",6)),
               start=c("08:00","09:00","09:00","08:00","10:00","12:30","13:30","18:00"),
               end=c("11:00","13:00","15:30","13:30","11:30","13:30","14:30","19:00"))

ds

```

```{r}
intercross <- function(data, name) {
  data <- data[data$anest == name, ]
  data$start <- as.POSIXct(data$start, format = "%H:%M")  #转换时间格式
  data$end <- as.POSIXct(data$end, format = "%H:%M")
  period <- sort(unique(c(data$start, data$end)))  #时间段排序
  n <- length(period)
  include <- data.frame()
  for(i in 1:nrow(data)){
    for(j in 1:(n-1)){
      include[i,j] <- (period[j] >= data$start[i] & period[j+1] <= data$end[i]) #找出每个资产存在于哪些时间段
    }
  }
  times <- apply(include, 2, sum)   #找出每个时间段存在的资产数目
  index <- which(times == max(times))
  final <- list(max(times), id = list())   #储存最终结果的列表
  for(k in 1:length(index)) {
    final$id[[k]] <- data$id[include[,index[k]]]   #找出重合次数最多的 id 并储存
  }
  final
}
intercross(ds, "baker")
intercross(ds, "dow")
```

